name: Deploy to Staging with Docker
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
        if_key_exists: replace
    
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} 'mkdir -p /opt/firesync-staging/app'
        rsync -avz --exclude=".git" --exclude=".github" --exclude="node_modules" ./ ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:/opt/firesync-staging/app/
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} 'cd /opt/firesync-staging && docker-compose down && docker-compose build && docker-compose up -d'